[package]
name = "hansb_me_3"
version = "0.1.0"
authors = ["Hans <hbhavan@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["migration", "site", "services", "writ"]

[dependencies]
dotenv = "*"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
services = { path = "./services/" }
site = { path = "./site/" }
writ = { path = "./writ/" }
